import Head from "next/head";
import HireMe from "@/sections/HireMe";

export default function Home() {

  return (
    <>
      <Head>
        <title>Shivam Gupta | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Shivam Gupta Web Developer and App Developer" />
      </Head>

      <HireMe />
    </>
  );
}
