import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import { LinkArrow } from "@/components/Icons";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import { motion, useAnimation } from "framer-motion";
import { useEffect } from "react";

export default function Home() {





  return (
    <>

      <Head>
        <title>Shivam Gupta | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Shivam Gupta Web Developer and App Developer" />
      </Head>

      <TransitionEffect />

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <motion.div className="w-1/2 md:w-full ml-20 lxmove"
            >
              <Image
                src={profilePic}
                alt="Shivam Gupta"
                className="w-4/5 h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </motion.div>
            <div className="w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center">

              <AnimatedText
                text="Empowering Creative Ideas with Strong Web and Native Apps "
                className="!text-5xl !text-left xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-5xl sm:!text-3xl"
              />

              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack web and app developer, I am dedicated to
                turning ideas into innovative web and native applications.
                Explore my latest projects and articles, showcasing my expertise
                in React.js, React Native and Node.js
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className="w-6" />
                </Link>
                <Link
                  href="mailto:shivamggupta2003@gmail.com"
                  className="ml-6 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="Vitt" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
