import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { FloatingDock } from "@/components/FloatingDock";
import { links } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>Shivam Gupta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Shivam Gupta Web Developer and App Developer" />
      </Head>
      <html lang="en" className="dark">
        <body>
          <main className="relative bg-black-100 flex justify-center items-center flex-col overflow-hidden mx-auto  min-h-screen">
            <div className="max-w-[100vw] w-full">
              {children}
              <FloatingDock desktopClassName='fixed bottom-[1.5rem] left-1/2 transform -translate-x-1/2 opacity-100 px-10' items={links} />
            </div>
          </main>
        </body>
      </html>
    </>
  );
}
