"use client";
import Head from "next/head";
import Blog from "@/sections/Blog";
import { ref, listAll } from "firebase/storage";
import { storage } from "@/lib/firebaseConfig";
import { useEffect, useState } from "react";

interface Topic {
  name: string;
  originalName: string;
  path: string;
}

export default function Home() {
  const [topicNames,setTopicNames] = useState<Topic[]>([]);
  useEffect(() => {
    const fetchBlogNames = async () => {
      try {
        const coursesRef = ref(storage, "courses/");
        const topicsResult = await listAll(coursesRef);

        const topics = topicsResult.prefixes.map((topicRef) => ({
          name: topicRef.name.replace(/_/g, " "), 
          originalName: topicRef.name, 
          path: topicRef.fullPath,
        }));

        topics.sort((a, b) => a.name.localeCompare(b.name));
        setTopicNames(topics);
      } catch (error) {
        console.error("Error fetching blog names:", error);
      }
    };

    fetchBlogNames();
  }, []);

  return (
    <>
      <Head>
        <title>Shivam Gupta | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Shivam Gupta Web Developer and App Developer"
        />
      </Head>

      <Blog topics={topicNames}/>
    </>
  );
}
