"use client";
import Head from "next/head";
import Blog from "@/sections/Blog";
import { getBlob, getDownloadURL, ref } from "firebase/storage";
import { storage } from "@/lib/firebaseConfig";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const fetchMarkdown = async () => {
      try {
        // Create a reference to the markdown file
        const mdFileRef = ref(storage, "gs://portfolio-a921f.appspot.com/blogs/lld.md");

        // Fetch the blob (binary data)
        const contentBlob = await getBlob(mdFileRef);
        console.log("Markdown Blob:", contentBlob);

        // Use FileReader to read the blob as text
        const reader = new FileReader();
        reader.onloadend = () => {
          const markdownContent = reader.result;
          console.log("Markdown File Content:", markdownContent);
        };
        
        // Read the blob as text
        reader.readAsText(contentBlob);
        
      } catch (error) {
        console.error("Error fetching markdown file:", error);
      }
    };

    fetchMarkdown();
  }, []);

  return (
    <>
      <Head>
        <title>Shivam Gupta | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Shivam Gupta Web Developer and App Developer"
        />
      </Head>

      <Blog />
    </>
  );
}
